package com.barbershop.enums;

public enum ViewRedirection {

    DASHBOARD,
    CLIENTS,
    CLIENT_CREATION,
    EMPLOYEES,
    EMPLOYEE_CREATION,
    APPOINTMENTS,
    APPOINTMENT_CREATION,
    BARBER_SERVICES,
    BARBER_SERVICE_CREATION,
    BARBER_SERVICE_EDITION,
    PRODUCTS,
    PRODUCT_CREATION,
    PRODUCT_EDITION,
    SETTINGS,
    LOGOUT
}
